version: '3.9'

services:
  api:
    image: ${DOCKER_REGISTRY}demodotnetapi:${TAG:-latest}
    build:
        context: .
        dockerfile: DemoDotnetApi/Dockerfile
    depends_on:
        - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trainingdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
